version: 2
jobs:
  build:
    docker:
      - image: olanilsson/emacs-ci:24.3-25.2
    working_directory: ~/proj
    environment:
      - CIRCLE_TEST_REPORTS: ~/proj/test_results
      - EMACS: /opt/emacs/25.2/bin/emacs
    steps:
      - checkout
      - run:
          name: Install cask
          command: curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
      - run:
          name: Test Matrix
          command: ./ci/ci-matrix.sh
      - store_test_results:
          path: ~/proj/test_results
      - store_artifacts:
          path: ~/proj/test_results
      - run:
          name: Deploy
          command: |
            if [ ${CIRCLE_BRANCH} = master ]; then
                ci/publish.sh -P -v -c -u "Ola Nilsson" -e "ola.nilsson@gmail.com" buttercup-junit.el
            else
                ci/publish.sh -v -c -u "Ola Nilsson" -e "ola.nilsson@gmail.com" buttercup-junit.el
            fi
