version: 2
jobs:
  build:
    docker:
      - image: olanilsson/emacs-ci:24.3-25.3
    working_directory: ~/proj
    environment:
      - CIRCLE_TEST_REPORTS: ~/proj/test_results
      - EMACS: /opt/emacs/25.3/bin/emacs
      - EMACSVERSIONS: 25.3 25.2 25.1 24.5 24.4 24.3
      - CASK: /root/.cask/bin/cask.sh
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-repo-cask-{{ .Branch }}-
            - v1-repo-cask-
      - restore_cache:
          keys:
            - v1-repo-deps-{{ .Branch }}-
            - v1-repo-deps-
      - run:
          name: Install cask
          environment:
            - CASKURL: https://raw.githubusercontent.com/snogge/cask/master/go.sh
          command: |
            if [ -f $CASK ] ; then
                echo $CASK upgrade
                $CASK upgrade
            else
                rm -rf ~/.cask
                echo curl -fsSL $CASKURL
                curl -fsSL $CASKURL | /bin/sh
            fi
            rm -rf /root/.emacs.d/.cask/*/elpa/archives
            ls -laR /root/.cask /root/.emacs.d/.cask > .cask.hash
            for ever in $EMACSVERSIONS; do
                if [ -d ~/proj/.cask/$ever/elpa ] ; then
                    echo CASK_EMACS=/opt/emacs/$ever/bin/emacs $CASK update
                    CASK_EMACS=/opt/emacs/$ever/bin/emacs $CASK update
                else
                    echo CASK_EMACS=/opt/emacs/$ever/bin/emacs $CASK install
                    CASK_EMACS=/opt/emacs/$ever/bin/emacs $CASK install
                fi
            done
            rm -rf ~/proj/.cask/*/elpa/archives
            ls -laR ~/proj/.cask > .elpa.hash
      - save_cache:
          key: v1-repo-cask-{{ .Branch }}-{{ checksum ".cask.hash" }}
          paths:
            - /root/.cask
            - /root/.emacs.d/.cask
      - save_cache:
          key: v1-repo-deps-{{ .Branch }}-{{ checksum ".elpa.hash" }}
          paths:
            - ~/proj/.cask
      - run:
          name: Test Matrix
          command: ./ci/ci-matrix.sh
      - store_test_results:
          path: ~/proj/test_results
      - store_artifacts:
          path: ~/proj/test_results
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BUILD_NUM}" ]; then
                if [ "${CIRCLE_BRANCH}" = master ]; then
                    ci/publish.sh -v -c -u "Ola Nilsson" -e "ola.nilsson@gmail.com" buttercup-junit.el
                else
                    ci/publish.sh -P -v -c -u "Ola Nilsson" -e "ola.nilsson@gmail.com" buttercup-junit.el
                fi
            fi
