---
teststeps: &teststeps
  working_directory: ~/proj
  steps:
    - checkout
    - run:
        name: Install programs
        # Busybox tar wont cut it
        command: |+
          apk add --no-cache tar || true
    - run:
        name: Build
        command: make build
    - run:
        name: Test
        command: |
          mkdir -p ~/proj/test_results
          emacs --version > ~/proj/test_results/.emacsversion
          make build
          make lint -k
          outer=$(emacs --version | head -1 | tr ' ' '_')
          make report OUTER="$outer" JUNIT=~/proj/test_results/tests.xml
    - store_test_results:
        path: ~/proj/test_results
    - store_artifacts:
        path: ~/proj/test_results

version: 2
jobs:
  emacs_master:
    docker:
      - image: silex/emacs:master-alpine-ci
    <<: *teststeps
  emacs_28.2:
    docker:
      - image: silex/emacs:28.2-alpine-ci
    <<: *teststeps
  emacs_28.1:
    docker:
      - image: silex/emacs:28.1-alpine-ci
    <<: *teststeps
  emacs_27.2:
    docker:
      - image: silex/emacs:27.2-alpine-ci
    <<: *teststeps
  emacs_26.3:
    docker:
      - image: silex/emacs:26.3-alpine-ci
    <<: *teststeps
  emacs_25.3:
    docker:
      - image: silex/emacs:25.3-alpine-ci
    <<: *teststeps
  emacs_24.5:
    docker:
      - image: silex/emacs:24.5-ci
    <<: *teststeps
  deploy:
    docker:
      - image: silex/emacs:28.2-ci
    steps:
      - checkout
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" = master ]; then
              ci/publish.sh -v -c -u "Ola Nilsson" -e "ola.nilsson@gmail.com" buttercup-junit.el
            else
              ci/publish.sh -P -v -c -u "Ola Nilsson" -e "ola.nilsson@gmail.com" buttercup-junit.el
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - emacs_master
      - emacs_28.2
      - emacs_28.1
      - emacs_27.2
      - emacs_26.3
      - emacs_25.3
      - emacs_24.5
      - deploy:
          requires:
            - emacs_master
            - emacs_28.2
            - emacs_28.1
            - emacs_27.2
            - emacs_26.3
            - emacs_25.3
            - emacs_24.5
  weekly:
    triggers:
      - schedule:
          # Run on Saturdays at 15:00 UTC
          cron: "15 0 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - emacs_master
      - emacs_28.2
      - emacs_28.1
      - emacs_27.2
      - emacs_26.3
      - emacs_25.3
      - emacs_24.5
