---
teststeps: &teststeps
  working_directory: ~/proj
  steps:
    - checkout
    - run: |
        mkdir -p ~/proj/test_results
        $EMACS --version > ~/proj/test_results/.emacsversion
    - run:
        name: Install cask
        environment:
          - CASKURL: https://raw.githubusercontent.com/snogge/cask/master/go.sh
          - CASK: /root/.cask/bin/cask.sh
        command: |
          if [ -f $CASK ] ; then
            echo $CASK upgrade
            $CASK upgrade
          else
            rm -rf ~/.cask
            echo curl -fsSL $CASKURL
            curl -fsSL $CASKURL | /bin/sh
          fi
          rm -rf /root/.emacs.d/.cask/*/elpa/archives
    - run:
        name: Install Dependencies
        environment:
          - CASK: /root/.cask/bin/cask.sh
        command: |
          if [ -d $($CASK package-directory) ] ; then
            echo $CASK update
            $CASK update
          else
            echo $CASK install
            $CASK install
          fi
          rm -rf ~/proj/.cask/*/elpa/archives
    - run:
        name: test
        command: |
          make build
          outer=$($EMACS --version | head -1 | tr ' ' '_')
          make report OUTER="$outer" JUNIT=~/proj/test_results/tests.xml
    - store_test_results:
        path: ~/proj/test_results
    - store_artifacts:
        path: ~/proj/test_results

version: 2
jobs:
  emacs_master:
    docker:
      - image: olanilsson/emacs:master-alpine-ci
    environment:
      - EMACS: emacs
      - CASK_EMACS: emacs
    <<: *teststeps
  emacs_26.1:
    docker:
      - image: olanilsson/emacs:26.1-alpine-ci
    environment:
      - EMACS: emacs
      - CASK_EMACS: emacs
    <<: *teststeps
  emacs_25.3:
    docker:
      - image: olanilsson/emacs:25.3-alpine-ci
    environment:
      - EMACS: emacs
      - CASK_EMACS: emacs
    <<: *teststeps
  emacs_25.2:
    docker:
      - image: olanilsson/emacs:25.2-alpine-ci
    environment:
      - EMACS: emacs
      - CASK_EMACS: emacs
    <<: *teststeps
  emacs_25.1:
    docker:
      - image: olanilsson/emacs:25.1-ci
    environment:
      - EMACS: emacs
      - CASK_EMACS: emacs
    <<: *teststeps
  emacs_24.5:
    docker:
      - image: olanilsson/emacs:24.5-ci
    environment:
      - EMACS: emacs
      - CASK_EMACS: emacs
    <<: *teststeps
  emacs_24.4:
    docker:
      - image: olanilsson/emacs:24.4-ci
    environment:
      - EMACS: emacs
      - CASK_EMACS: emacs
    <<: *teststeps
  emacs_24.3:
    docker:
      - image: olanilsson/emacs:24.3-ci
    environment:
      - EMACS: emacs
      - CASK_EMACS: emacs
    <<: *teststeps
  deploy:
    docker:
      - image: olanilsson/emacs:26.1-alpine-ci
    environment:
      - EMACS: emacs
      - CASK_EMACS: emacs
    steps:
      - checkout
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" = master ]; then
              ci/publish.sh -v -c -u "Ola Nilsson" -e "ola.nilsson@gmail.com" buttercup-junit.el
            else
              ci/publish.sh -P -v -c -u "Ola Nilsson" -e "ola.nilsson@gmail.com" buttercup-junit.el
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - emacs_master
      - emacs_26.1
      - emacs_25.3
      - emacs_25.2
      - emacs_25.1
      - emacs_24.5
      - emacs_24.4
      - emacs_24.3
      - deploy:
          requires:
            - emacs_master
            - emacs_26.1
            - emacs_25.3
            - emacs_25.2
            - emacs_25.1
            - emacs_24.5
            - emacs_24.4
            - emacs_24.3
  weekly:
    triggers:
      - schedule:
          # Run on Saturdays at 15:00 UTC
          cron: "15 0 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - emacs_master
      - emacs_26.1
      - emacs_25.3
      - emacs_25.2
      - emacs_25.1
      - emacs_24.5
      - emacs_24.4
      - emacs_24.3
